spring:
  security:
    oauth2:
      client:
        registration:
           github:
              client-id: a3244d29cb865c119f4a
              client-secret: 1bf5ec360320bcfa3163c7394dd4a90efbbab4ca 