spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: qwerty12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:    show-sql: true
    
    
    
